# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: smartmanru
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: columns
          config_timezone: Europe/Moscow
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 1000
          plugin_stars: yes
          plugin_stars_limit: 4
          repositories: 1000
          repositories_batch: 1000
